### ISSUE TITLE
creating data

### ISSUE THREAD

**Issue by amirim** [A2Zadeh/TensorFusionNetwork#3]
can you post the code that generates the features for each modality - language visual and audio ?

**Comment by A2Zadeh** [comment]
Hello @amirim. I assume you mean the code that generates tensors that can be fed into a deep learning library like PyTorch or TensorFlow? If so, yes, we are currently in the final stages of debugging that. Should be ready no later than weekend.

**Comment by A2Zadeh** [comment]
Also it would be in the CMU Multimodal Data SDK.
