### ISSUE TITLE
Something about the paper results

### ISSUE THREAD

**Issue by KuzmaNg** [A2Zadeh/TensorFusionNetwork#4]
Hi, Amir. Here, I wanna ask something about the results from the TFN paper. From the following table, we know that TFNtrimodal is created with 3 modalities fusion, but I am not sure how TFN works (which boosts to 77.1 in Acc). Is the whole TFN combined with all Unimodal, Bimodal and Trimodal subtensors? 
![table2](https://i.imgur.com/KIZI5zC.png)

**Comment by A2Zadeh** [comment]
Hello @KuzmaNg. Yes that is correct. Does that answer the question? If you need more explanation let's chat over email.
